lr: 0.0005
x_dim: 2
y_dim: 3
sigma_eps: 0.0001

data_horizon: 20
test_horizon: 5
meta_batch_size: 10

nn_layers: [128, 128, 16]
activation: 'tanh'

# Environment parameters
thrust_range: [0.0006, 0.0015]
gravity_range: [0.002, 0.003]
pos_range: [-1.2, 0.6]
vel_range: [-0.07, 0.07]

# VI parameters
data_dir: './metamountaincar/mmcDataset/close/'
num_data: 110
gran: 150
step_limit: 200


# Empirical normalizing constants
pos_var: 0.5 
vel_var: 0.0333
q_mean: -45
q_var: 25
